services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - homepage-config:/app/config # Make sure your local config directory exists
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ts.${DOMAIN_NAME} # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    networks:
      - core_traefik-public
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`ts.${DOMAIN_NAME}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=cf-ts
      - traefik.http.services.homepage.loadbalancer.server.port=3000
volumes:
  homepage-config:
networks:
  core_traefik-public:
    external: true
