services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: "America/Chicago"
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_webserver_api_password: ${DNS_ADMIN_PASSWORD} # This comes from the nix shell environment
      # Quad9 DNS servers with DNSSEC validation
      FTLCONF_dns_upstreams: 9.9.9.9;149.112.112.112 # Points to Quad9 dns server w/out ECS but with DNSSEC
    # Volumes store your data between container upgrades
    volumes:
      - config:/etc/pihole
    networks:
      - proxy_default
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      - traefik.enable=true
      # router: redirect HTTP -> HTTPS
      - "traefik.http.routers.pihole-http.rule=Host(`dns.admin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.pihole-http.entrypoints=web"
      - "traefik.http.routers.pihole-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # secure router (HTTPS) for entire host
      - "traefik.http.routers.pihole.rule=Host(`dns.admin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=le"
      # If you prefer only /admin behind Traefik:
      # - "traefik.http.routers.pihole.rule=Host(`pihole.example.com`) && (PathPrefix(`/admin`) || PathPrefix(`/admin/`))"

      # service port inside the container (lighttpd => 80)
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # headers middleware so Pi-hole sees X-Forwarded-Proto=https and generates https links
      - "traefik.http.middlewares.pihole-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.pihole.middlewares=pihole-headers"
networks:
  proxy_default:
    external: true
volumes:
  config:
