version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    command: vault server -config=/vault/config/vault.hcl
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config:/vault/config/
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    networks:
      - backend_network
      - reverse_proxy_network
    labels:
      caddy: vault.admin.${DOMAIN_NAME:?"DOMAIN_NAME environment variable is not set"}
      caddy.reverse_proxy: "{{upstreams 8200}}"
      caddy.tls.protocols: tls1.3

networks:
  backend_network:
    external: true
  reverse_proxy_network:
    external: true

volumes:
  vault-data: