version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config:/vault/config/
      - vault-data:/vault/data
    environment:
      - VAULT_CONFIG_FILE=/vault/config/vault.hcl
      - VAULT_ADDR=http://0.0.0.0:8200
    networks:
      - backend_network
      - reverse_proxy_network
    labels:
      caddy: vault.admin.${DOMAIN_NAME:?"DOMAIN_NAME environment variable is not set"}
      caddy.reverse_proxy: "{{upstreams 8200}}"
      caddy.tls.protocol: tls1.3

networks:
  backend_network:
    external: true
  reverse_proxy_network:
    external: true

volumes:
  vault-data: