version: "3.8"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev:/dev:ro
    networks:
      - default
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        - prometheus_job=cadvisor
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - NODES=1
      - SWARM=1
      - EVENTS=1
      - NETWORKS=1
    networks:
      - default
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    configs:
      - source: promtail-config
        target: /etc/promtail/config.yml
    volumes:
      - promtail-data:/var/lib/promtail
    networks:
      - default
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/config.yml
    user: root
    configs:
      - source: loki-config
        target: /etc/loki/config.yml
    volumes:
      - loki-data:/loki
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    environment: # Required if Grafana is running behind a reverse proxy
      GF_SERVER_ROOT_URL: https://monitoring.admin.${DOMAIN_NAME}
      GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: "true"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default
      - proxy_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true

        - traefik.http.routers.grafana.rule=Host(`monitoring.admin.${DOMAIN_NAME}`)
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=le

        - traefik.http.services.grafana.loadbalancer.server.port=3000

configs:
  prometheus-config:
    file: ./prometheus.yml
  promtail-config:
    file: ./promtail.yml
  loki-config:
    file: ./loki.yml

volumes:
  prometheus-data:
  promtail-data:
  loki-data:
  grafana-data:

networks:
  proxy_public:
    external: true
  default:
    driver: overlay
    attachable: true
