# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    dockerswarm_sd_configs:
      - role: tasks
    relabel_configs:
      - source_labels: [_meta_docker_task_name]
        action: keep
        regex: ^monitoring_cadvisor\..*$
      - source_labels: [_meta_docker_task_name]
        action: replace
        target_label: instance
        regex: ^(.*)\..*$
